### PR TITLE
Indonesian translation

### PR DESCRIPTION
**Pull request by cppethereum**
Issue Number: #701

# Description

Indonesian Translation

Note: idn flag already exists at `assets/images/flags/idn.png`

I will keep an eye in case I need to fix merge conflicts etc.

`45z6hCLTGktXYsbXWE9yCx19J9wDTzuENhzdi4uuB4to72apchuBYRjTAxyXBMWudbgp8h4JDMFtCFs8SBYyTcH3Urx657j`

### CODE REVIEW

**Comment by cppethereum** [comment]
@OmarHatem28 hi Omar, would you be interested in reviewing? Thanks in advance for any help.

**Review by OmarHatem28 — COMMENTED** [review]
@cppethereum Thanks for contributing, please sync the PR with the latest main as there are new localizations added, but everything else looks good.

**Comment by cppethereum** [comment]
@OmarHatem28 Thanks! I've fixed the conflicts.

**Review by OmarHatem28 — APPROVED** [review]

**Comment by SamsungGalaxyPlayer** [comment]
@cppethereum this has been paid, thank you!

**Pull request merged**
