### PR TITLE
Update app_env.sh

### PR DESCRIPTION
**Pull request by plowsof**
When using /bin/sh in Ubuntu im getting this error: (using bash fixes this)
./app_env.sh: 12: Syntax error: "(" unexpected

### CODE REVIEW

**Comment by mkyq** [comment]
I made mistake into build instruction there need to run `$ source ./app_env.sh <TYPE>` instead of just `./app_env.sh <TYPE>`

**Comment by plowsof** [comment]
Thank you, that fixes it. Now i am having another problem with building:

Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not create task ':app:processReleaseMainManifest'.              
   > java.lang.NullPointerException (no error message)   

My flutter doctor seems ok:
[✓] Flutter (Channel unknown, 2.0.4, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio

Any ideas? hm

**Comment by plowsof** [comment]
I am able to see errors when i build with 'monero.com' 

(cw_bitcoin.dart is there)
lib/main.dart:2:8: Error: Error when reading 'lib/bitcoin/bitcoin.dart': No such file or directory

(cw_monero.dart is there)
lib/di.dart:1:8: Error: Error when reading 'lib/monero/monero.dart': No such file or directory

(i can't seem to see this file.. only wallet_types_utils.dart) 
lib/wallet_type_utils.dart:2:8: Error: Error when reading 'lib/wallet_types.g.dart': No such file or directory

**Comment by mkyq** [comment]
@plowsof did you run mobx script for build mobx models ? I added into android instruction that need to do it for cw_core, cw_monero and cw_bitcoin dirs too

**Comment by plowsof** [comment]
Thanks, (i was using my fork so did not see those updates. sorry) - i have deleted everything to start from the beginning.
after using `source ./app_env.sh cakewallet` :

app_config.sh output:
```
rm: cannot remove '/opt/android/cake_wallet/scripts/android/../../assets/images/app_logo.png': No such file or directory
rm: cannot remove '/opt/android/cake_wallet/scripts/android/../../android/app/src/main/res/drawable/ic_launcher.png': No such file or directory
No .dart_tool/package_config.json file found, please run "pub get".

Starting with Dart 2.7, the package_config.json file configures resolution of package import URIs; run "pub get" to generate it.
pub finished with exit code 65
```

**Pull request merged**
