### PR TITLE
CW-284 Fix QR code UI and logic issues

### PR DESCRIPTION
**Pull request by OmarHatem28**
Issue Number (if Applicable): Fixes #N/A

# Description

- Replace QR package with another ready-made one to exclude the error being from painting QR
- Revert QR version change so its re-producible if it happens again
- Fixate QR background and foreground colors

# Pull Request - Checklist  

- [x] Initial Manual Tests Passed

### CODE REVIEW

**Review by SamsungGalaxyPlayer — APPROVED** [review]
Creating and scanning QR codes works with this patch on my android device

**Comment by OmarHatem28** [comment]
@SamsungGalaxyPlayer I updated the PR with another solution, reverting back to the old QR version (which should work fine anyway), please give it a try when possible

**Review by mkyq — APPROVED** [review]

**Comment by SamsungGalaxyPlayer** [comment]
Needs fix for display; check Slack

**Comment by OmarHatem28** [comment]
@SamsungGalaxyPlayer please check the new build with the 3 themes

**Pull request merged**
