### PR TITLE
Add thai language localization file

### PR DESCRIPTION
**Pull request by maddymodd**
As per https://bounties.monero.social/posts/72/2-364m-thai-language-in-cake-wallet I have added the thai language support file.

### CODE REVIEW

**Comment by maddymodd** [comment]
The workflow needs the android key.jks to run. I am a sole developer outside of the cake wallet project so I don't have access to this.

**Comment by SamsungGalaxyPlayer** [comment]
@maddymodd we have a pending build update that I thought was merged already. Thanks for investigating; you can ignore for now.

**Comment by OmarHatem28** [comment]
@maddymodd please update your fork with the latest `cake-tech:main` and update the PR, that should solve the build failure

**Comment by maddymodd** [comment]
> @maddymodd please update your fork with the latest `cake-tech/cake_wallet:main` and update the PR, that should solve the build failure

updated

**Review by OmarHatem28 — CHANGES_REQUESTED** [review]
@maddymodd the PR is missing the flag for thai language, please follow this [guide](https://github.com/cake-tech/cake_wallet/blob/main/README.md#add-a-new-language) in `READEME.md` regarding adding a new language

**Comment by maddymodd** [comment]
> @maddymodd the PR is missing the flag for thai language, please follow this [guide](https://github.com/cake-tech/cake_wallet/blob/main/README.md#add-a-new-language) in `READEME.md` regarding adding a new language

I saw that the thai flag was already in the assets folder, here: https://github.com/cake-tech/cake_wallet/blob/main/assets/images/flags/tha.png

**Comment by OmarHatem28** [comment]
yup, didn't see that flag, thanks for noticing

**Review by OmarHatem28 — CHANGES_REQUESTED** [review]
there are errors in this file due to missing `,` after some translations
error lines are `264`, `282`, `530`, and `583`

**Comment by maddymodd** [comment]
> there are errors in this file due to missing `,` after some translations error lines are `264`, `282`, `530`, and `583`

Whoops! Sorry about that. Those lines should be fixed now.

**Comment by plowsof** [comment]
"optionally_order_card": "Optionally order a physical card.", is missing

**Comment by maddymodd** [comment]
> "optionally_order_card": "Optionally order a physical card.", is missing

Thanks for spotting that. I added the line.

**Review by OmarHatem28 — APPROVED** [review]

**Pull request merged**
