### PR TITLE
fix empty string case

### PR DESCRIPTION
**Pull request by fossephate**
Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

### CODE REVIEW

**Review by OmarHatem28 — CHANGES_REQUESTED** [review]
revert the commit that mergs mac-auth branch

**Comment by fossephate** [comment]
Agh I thought the mac auth PR would be merged by now and this was just a quick hack to fix things locally since that branch has the fixes for building on 3.19.5

**Comment by fossephate** [comment]
Also: I did the same thing for the signing branch, but that one actually has package updates that need a newer flutter version anyways

**Comment by OmarHatem28** [comment]
we reverted that since it had some issues, and you fixed some of them later in a separate PR #1398 but still, we are holding on merging it until the issue with biometric auth turned off with restart is fixed

**Comment by fossephate** [comment]
> we reverted that since it had some issues, and you fixed some of them later in a separate PR #1398 but still, we are holding on merging it until the issue with biometric auth turned off with restart is fixed

I wasn't able to reproduce the issue more than once so I can't confirm, but I think that issue is unrelated to the changes in the PR (my working theory is that for whatever reason, sometimes secure storage just fails to write), I'll try again to reproduce it tomorrow though and hopefully find a fix

**Comment by OmarHatem28** [comment]
> > we reverted that since it had some issues, and you fixed some of them later in a separate PR #1398 but still, we are holding on merging it until the issue with biometric auth turned off with restart is fixed
> 
> I wasn't able to reproduce the issue more than once so I can't confirm, but I think that issue is unrelated to the changes in the PR (my working theory is that for whatever reason, sometimes secure storage just fails to write), I'll try again to reproduce it tomorrow though and hopefully find a fix

either way, this is a separate PR, so let's revert the merge commit and merge this

**Review by OmarHatem28 — APPROVED** [review]

**Pull request merged**
