### PR TITLE
Add Czech language

### PR DESCRIPTION
**Pull request by holecekp**
# Description

Czech language has been added.

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed

I have not able to test the translation yet because of https://github.com/cake-tech/cake_wallet/issues/761. I will test it once the APK is created by pr_test_build.yml.

### CODE REVIEW

**Comment by SamsungGalaxyPlayer** [comment]
Auto-built APK (downloads a ZIP): https://github.com/cake-tech/cake_wallet/suites/10779386839/artifacts/541708716

**Comment by holecekp** [comment]
I have installed the APK from the link into an older phone but the tests did not went well. The app starts into English and a warning is displayed after installation that can be translated as: "This app contains a virus. Uninstall it immediately". Do you have any idea what could cause it?
cake1

I have ignored it thinking that the old Huawei phone probably just does not like sideloaded apps. I do not use this phone for other things than testing anyway so I continued. The bigger problem is that I have selected to create a new wallet, then I was prompted to choose a PIN, but any 4 or 6 digit PIN is refused with the following error so I am not able to continue:
cake2
If I select to recover a wallet instead of creating a new one, I am again required to select a pin, which ends up with the same error.

**Comment by Justxd22** [comment]
@holecekp yes this happens for me, every workflow GitHub builds produce same error, I'm guessing it has something to do with the wrong keys used in the build or it's a test build  (unusable), I tested multiple devices Android 13, 11, 10 same error, 

you can ignore the virus thing it's safe, any new builds is triggered as virus as it was not scanned before

**Comment by OmarHatem28** [comment]
@holecekp yeah as Justxd22 said, it is triggered as a virus as it was not scanned before and installed from an unknown source

regarding the generated apk error, the workflow build is configured to add some keys from the GitHub secrets and any **External** PR does not have access to these secrets thus it builds the apk with empty secrets thus leading to those errors.

regarding the PR, looks good and tests well, please sync your PR with the latest updates in main and fix the conflicts

**Review by OmarHatem28 — APPROVED** [review]

**Comment by SamsungGalaxyPlayer** [comment]
Thank you for your contribution @holecekp!

**Pull request merged**
