### PR TITLE
Add Support for Arabic Language Bounty #699

### PR DESCRIPTION
**Pull request by Justxd22**
- Created & translated [`res/values/strings_ar.arb`](https://github.com/Justxd22/cake_wallet/commit/15d5375eb6dfe878c1c8aae2bb7f102a3e566cd9#diff-ec9f357ca28382a57a0e86818113f0e2f1cb4fc7ef53ac21f2bc18dabbba7e0f)
- Added language in [`lib/entities/language_service.dart`](https://github.com/Justxd22/cake_wallet/commit/15d5375eb6dfe878c1c8aae2bb7f102a3e566cd9#diff-08342b16f9e0a48cb8c879d13afa949f0baac91735b4f67cb56811aa69342198)
- Added language flag [`assets/images/flags/sau.png`](https://github.com/Justxd22/cake_wallet/commit/15d5375eb6dfe878c1c8aae2bb7f102a3e566cd9#diff-1fb3e24258173eb2a1606f9451a70935f0f13c50d0f5146a853d9099236753d5)
- Fixed Some typos in [`README.md`](https://github.com/Justxd22/cake_wallet/commit/15d5375eb6dfe878c1c8aae2bb7f102a3e566cd9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

Merging this would close [[$150 Bounty] Add Arabic (ar/arb) #699](https://github.com/cake-tech/cake_wallet/issues/699#issue-1521264647)

i sent Bounty Details on [justin@cakewallet.com](mailto:justin@cakewallet.com) from xdjust18@gmail.com

Thanks!

### CODE REVIEW

**Comment by SamsungGalaxyPlayer** [comment]
Should we use an Egypt flag instead of a Saudi Arabia flag?

https://www.worldatlas.com/articles/arabic-speaking-countries.html
https://www.worlddata.info/languages/arabic.php

**Comment by Justxd22** [comment]
@SamsungGalaxyPlayer Sure thing, i saw ksa flag being used in alot of websites (as lang indicator) before so i taught it's a standard thing, i will make new flag now

**Comment by Justxd22** [comment]
@SamsungGalaxyPlayer Done!

**Comment by Relected** [comment]
damn its already done? I wanted to get it first lol

ggs m8

**Comment by Justxd22** [comment]
@Relected haha, there's still other languages if you want to contribute

**Comment by Babypoo-byte** [comment]
> @Relected haha, there's still other languages if you want to contribute

congrats , bdw can you take a look at my work, in case there are any mistakes

**Comment by Justxd22** [comment]
@Babypoo-byte looks okay, but you opened multiple pull requests, it would be better if you made all commits in one pr, wait for someone to review your work, i'm still waiting too.....

**Comment by Relected** [comment]
> haha, there's still other languages if you want to contribute

yeah thought I'm egyptian so I only know egyptian Arabic and English :/

**Review by SamsungGalaxyPlayer — APPROVED** [review]

**Comment by Justxd22** [comment]
@SamsungGalaxyPlayer i think i need workflow approve too for a test build?

**Comment by Justxd22** [comment]
Update: 

i tried upgrading over the playstore version, it asks for pin then i see 'Authentication' message at the top and it hangs there

**Comment by Justxd22** [comment]
i think we're done it can be merged

**Review by OmarHatem28 — APPROVED** [review]

**Comment by OmarHatem28** [comment]
Hi @Justxd22 I reviewed the PR and everything looks great, 1 minor thing, please revert back to Saudi Arabia Flag as it's indeed used most often when indicating the Arabic language

**Comment by Justxd22** [comment]
@OmarHatem28 alright

**Comment by Justxd22** [comment]
@OmarHatem28 all good

**Pull request merged**
