### PR TITLE
Cw 385 - change wallet screen not responding

### PR DESCRIPTION
**Pull request by rafael-xmr**
Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [X] Initial Manual Tests Passed
- [X] Double check modified code and verify it with the feature/task requirements
- [X] Format code
- [X] Look for code duplication
- [X] Clear naming for variables and methods

### CODE REVIEW

**Comment by OmarHatem28** [comment]
Should I close #954 in favor of this PR?

**Comment by saltrafael** [comment]
yep this was branched off the latest linux branch to avoid conflicts again

**Comment by OmarHatem28** [comment]
when changing the base to the new Linux branch #1078 it changed to over 500 files changed, but anyway, I can see that this branch has only 1 commit, if so let's cherry-pick it on a new branch based on the new `cw_linux_direct_input_password` and close this and delete the branch after

**Comment by OmarHatem28** [comment]
closing as I believe this was fixed already or at least not reported anymore

**Pull request closed without merging**
