### PR TITLE
multi: Add initial decred screens.

### PR DESCRIPTION
**Pull request by JoeGruffins**
Only the last commit is new, the rest are commits in main.

We are working on a libwallet that will go golang -> c -> dart that we plan on using with a few projects. We hope to drop that in to replace the mock dcrlibwallet currently in `/cw_decred/lib/api`.

Any feedback is appreciated.

part of #986

### CODE REVIEW

**Comment by JoeGruffins** [comment]
Removed the `DerivationType` decred type  https://github.com/cake-tech/cake_wallet/compare/96e6fad33a40987aac8787fc03280ad368a804b8..6c1843deb52481077d130279572a5990a2476d43

**Comment by JoeGruffins** [comment]
Fixed a rebase miss. https://github.com/cake-tech/cake_wallet/compare/6151bb7d11c2667c31f2782ec0038f4876e22f10..5c18d352621173296c49d257be48de57474e06e4

**Comment by JoeGruffins** [comment]
One more rebase goof fixed https://github.com/cake-tech/cake_wallet/compare/5c18d352621173296c49d257be48de57474e06e4..77fcd84243dcf24091eb201569b142483dd8b379

**Comment by JoeGruffins** [comment]
Rebased on main because we were having trouble building monero.

**Review by OmarHatem28 — APPROVED** [review]

**Pull request merged**
