### PR TITLE
Add Support for Hausa Language Bounty #708

### PR DESCRIPTION
**Pull request by Justxd22**
### OLD PR #728 and #740
 - Created & translated res/values/strings_ha.arb
 - Added language in lib/entities/language_service.dart
 - Added language flag assets/images/flags/hau.png

Hausa is mainly spoken in northern Nigeria, the Republic of Niger, northern Cameroon, and Ghana, but since #709 i can't use Nigeria flag, therefore Hausa flag is used with hau 639-2/T code

Merging this would close https://github.com/cake-tech/cake_wallet/issues/708

Thanks!

### CODE REVIEW

**Comment by OmarHatem28** [comment]
why did you close #740 you were going in the right direction, only some errors for the Cupertino Localizations.

for this PR, changing to Hausa language results in the following error, since it's not supported by Flutter by default check [this](https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html) and [this](https://docs.flutter.dev/accessibility-and-localization/internationalization#adding-support-for-a-new-language)

Screen Shot 2023-05-04 at 3 28 03 AM

**Comment by OmarHatem28** [comment]
Closed by #936 
Thanks for contributing

**Comment by Justxd22** [comment]
Merged in #936

**Comment by Justxd22** [comment]
thanks

**Pull request closed without merging**
