### PR TITLE
fix for building on ios

### PR DESCRIPTION
**Pull request by fossephate**
Issue Number (if Applicable): Fixes #

# Description

Please include a summary of the changes and which issue is fixed / feature is added. 

# Pull Request - Checklist  

- [ ] Initial Manual Tests Passed
- [ ] Double check modified code and verify it with the feature/task requirements
- [ ] Format code
- [ ] Look for code duplication
- [ ] Clear naming for variables and methods

### CODE REVIEW

**Comment by OmarHatem28** [comment]
we tried this and it didn't work, right?
we said that we are going to specify the commit from which to clone the repo

**Comment by fossephate** [comment]
@OmarHatem28 IIRC, I couldn't get it to work even when I did specify the commit hash :/

**Comment by itswisdomagain** [comment]
> we said that we are going to specify the commit from which to clone the repo

This commit worked for me: `443617d7507498f7477703f0b51cb596d4539262`.

**Comment by OmarHatem28** [comment]
@itswisdomagain thanks for providing some insights on this.

@fossephate we would need to test this again to verify that it's working with your changes, but we will still need to specify a commit to avoid any unexpected behavior if the `stable` branch is updated

**Pull request closed without merging**
