### PR TITLE
Add Support for Hausa Language Bounty #708

### PR DESCRIPTION
**Pull request by Justxd22**
- Created & translated [res/values/strings_ha.arb](https://github.com/Justxd22/cake_wallet/commit/69ad306e51bcb1e8c1e1c65b1f28e8dce6f82f68#diff-977872d4eb9cd77900f1bcbac035bde3fb31f8af2a03c0612512ee2eb99cfecc)
 - Added language in [lib/entities/language_service.dart](https://github.com/Justxd22/cake_wallet/commit/47391059ced066d956884e63124206273af3f5da#diff-08342b16f9e0a48cb8c879d13afa949f0baac91735b4f67cb56811aa69342198)
 - Added language flag [assets/images/flags/hau.png](https://github.com/Justxd22/cake_wallet/commit/47391059ced066d956884e63124206273af3f5da#diff-7242d6010bb66ee18f16bbcbd5eb551f4208a5f199b04c1f79b427d3e8ee162d)
 

Hausa is mainly spoken in northern Nigeria, the Republic of Niger, northern Cameroon, and Ghana, but since #709 i can't use Nigeria flag, therefore Hausa flag is used with hau 639-2/T code

Merging this would close https://github.com/cake-tech/cake_wallet/issues/708

Thanks!

### CODE REVIEW

**Comment by Justxd22** [comment]
@SamsungGalaxyPlayer workflow failed because not using main branch, should i do another pr?

**Comment by Justxd22** [comment]
@SamsungGalaxyPlayer please review when you can

**Comment by Justxd22** [comment]
i need someone to review this pr

**Review by OmarHatem28 — CHANGES_REQUESTED** [review]
Switching to the language results in an error, please fix the error and sync your PR

**Comment by Justxd22** [comment]
@OmarHatem28 check #740

**Pull request closed without merging**
