### PR TITLE
Cw 3 update UI sending template

### PR DESCRIPTION
**Pull request by godilite**
update sending template
Remove (text) Template, add + icon if n >= 1 templates exist

**Screen shots**
IMG_3940

IMG_3941

### CODE REVIEW

**Comment by mkyq** [comment]
@godilite please update you branch to mainstream

**Comment by mkyq** [comment]
not sure that you added translation for all localization files

**Comment by mkyq** [comment]
Good that you fixed your issue with wallet manager, but for next time please send only code related for the task. For fixes like that better to create new branches and send PR from them. Also maybe better to disable auto code formatter, at least for files which you currently do not edit, because it's hard to find out what you exactly changed for the task.

**Review by mkyq — CHANGES_REQUESTED** [review]
See comments to the PR

**Comment by godilite** [comment]
> not sure that you added translation for all localization files

updated

**Pull request closed without merging**
